import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Upload, Download, CheckCircle, Clock, Play, Languages, Subtitles, Eye, MoreVertical } from 'lucide-react'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Progress } from '@/components/ui/progress'

interface CaptionFile {
  id: string
  videoName: string
  language: string
  status: 'generating' | 'completed' | 'review' | 'uploaded'
  accuracy: number
  duration: string
  uploadDate: string
  isAutoGenerated: boolean
}

const CaptionsForm = () => {
  const [autoGenerateEnabled, setAutoGenerateEnabled] = useState(true)
  const [captions, setCaptions] = useState<CaptionFile[]>([
    {
      id: '1',
      videoName: '01_Introduction_Welcome_to_the_Course.mp4',
      language: 'Tiếng Anh',
      status: 'completed',
      accuracy: 95,
      duration: '2:30',
      uploadDate: '2024-01-15',
      isAutoGenerated: true
    },
    {
      id: '2',
      videoName: '02_Overview_Course_Structure.mp4',
      language: 'Tiếng Anh',
      status: 'generating',
      accuracy: 0,
      duration: '5:15',
      uploadDate: '2024-01-15',
      isAutoGenerated: true
    },
    {
      id: '3',
      videoName: '03_Getting_Started_Setup.mp4',
      language: 'Tiếng Anh',
      status: 'review',
      accuracy: 87,
      duration: '8:42',
      uploadDate: '2024-01-15',
      isAutoGenerated: true
    }
  ])

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed':
        return <CheckCircle className='h-4 w-4 text-green-600' />
      case 'generating':
        return <Clock className='h-4 w-4 text-blue-600' />
      case 'review':
        return <Eye className='h-4 w-4 text-yellow-600' />
      case 'uploaded':
        return <CheckCircle className='h-4 w-4 text-green-600' />
      default:
        return <Clock className='h-4 w-4' />
    }
  }

  const getStatusText = (status: string) => {
    switch (status) {
      case 'completed':
        return 'Sẵn sàng sử dụng'
      case 'generating':
        return 'Đang tạo phụ đề'
      case 'review':
        return 'Cần xem lại'
      case 'uploaded':
        return 'Đã tải lên thủ công'
      default:
        return 'Không xác định'
    }
  }

  const getAccuracyColor = (accuracy: number) => {
    if (accuracy >= 95) return 'text-green-600'
    if (accuracy >= 85) return 'text-yellow-600'
    return 'text-red-600'
  }

  const getCompletedCount = () => {
    return captions.filter((c) => c.status === 'completed' || c.status === 'uploaded').length
  }

  return (
    <div className='max-w-6xl space-y-8'>
      <div className='mb-8'>
        <h1 className='text-3xl font-bold mb-4'>Phụ đề</h1>
        <p className='text-muted-foreground text-lg mb-6'>
          Giúp khóa học của bạn dễ tiếp cận hơn với nhiều học viên bằng cách thêm phụ đề. 
          Chúng tôi có thể tự động tạo phụ đề cho video của bạn hoặc bạn có thể tải phụ đề của riêng mình. 
          Phụ đề hỗ trợ học viên khiếm thính và cải thiện khả năng tiếp thu cho tất cả học viên.
        </p>

        <div className='flex space-x-6 text-sm'>
          <div className='flex items-center space-x-2'>
            <span className='font-medium'>
              {getCompletedCount()}/{captions.length}
            </span>
            <span className='text-muted-foreground'>video có phụ đề</span>
          </div>
          <div className='flex items-center space-x-2'>
            <Languages className='h-4 w-4' />
            <span className='text-muted-foreground'>Tiếng Anh (chính)</span>
          </div>
        </div>
      </div>

      <Tabs defaultValue='auto' className='space-y-6'>
        <TabsList>
          <TabsTrigger value='auto'>Tự động tạo</TabsTrigger>
          <TabsTrigger value='upload'>Tải lên phụ đề</TabsTrigger>
          <TabsTrigger value='manage'>Quản lý phụ đề</TabsTrigger>
        </TabsList>

        <TabsContent value='auto' className='space-y-6'>
          <Card>
            <CardHeader>
              <CardTitle className='flex items-center justify-between'>
                <span>Tự động tạo phụ đề</span>
                <Switch checked={autoGenerateEnabled} onCheckedChange={setAutoGenerateEnabled} />
              </CardTitle>
              <p className='text-sm text-muted-foreground'>
                Tự động tạo phụ đề cho tất cả video khóa học bằng công nghệ nhận diện giọng nói AI
              </p>
            </CardHeader>
            <CardContent className='space-y-4'>
              <div className='grid md:grid-cols-2 gap-4'>
                <div className='space-y-2'>
                  <h4 className='font-medium'>Lợi ích của phụ đề tự động</h4>
                  <ul className='text-sm text-muted-foreground space-y-1'>
                    <li>• Tiết kiệm thời gian và công sức</li>
                    <li>• Có sẵn cho tất cả video ngay lập tức</li>
                    <li>• Hỗ trợ nhiều ngôn ngữ</li>
                    <li>• Cải thiện khả năng tiếp cận khóa học</li>
                  </ul>
                </div>
                <div className='space-y-2'>
                  <h4 className='font-medium'>Cài đặt phụ đề</h4>
                  <div className='space-y-3'>
                    <div className='flex items-center justify-between'>
                      <span className='text-sm'>Ngôn ngữ chính</span>
                      <Select defaultValue='en'>
                        <SelectTrigger className='w-32'>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value='en'>Tiếng Anh</SelectItem>
                          <SelectItem value='es'>Tiếng Tây Ban Nha</SelectItem>
                          <SelectItem value='fr'>Tiếng Pháp</SelectItem>
                          <SelectItem value='de'>Tiếng Đức</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div className='flex items-center justify-between'>
                      <span className='text-sm'>Ngưỡng tự động duyệt</span>
                      <Select defaultValue='85'>
                        <SelectTrigger className='w-24'>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value='95'>95%</SelectItem>
                          <SelectItem value='90'>90%</SelectItem>
                          <SelectItem value='85'>85%</SelectItem>
                          <SelectItem value='80'>80%</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                </div>
              </div>

              {autoGenerateEnabled && (
                <div className='mt-6 p-4 bg-blue-50 rounded-lg border border-blue-200'>
                  <div className='flex items-center space-x-2 mb-2'>
                    <Clock className='h-4 w-4 text-blue-600' />
                    <span className='font-medium text-blue-900'>Đã bật tự động tạo</span>
                  </div>
                  <p className='text-sm text-blue-700'>
                    Phụ đề sẽ được tự động tạo cho tất cả video mới bạn tải lên. 
                    Các video hiện tại đang được xử lý trong nền.
                  </p>
                </div>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Tạo phụ đề cho video hiện có</CardTitle>
            </CardHeader>
            <CardContent>
              <div className='space-y-4'>
                <p className='text-sm text-muted-foreground'>Tạo phụ đề cho những video chưa có</p>
                <Button className='bg-primary hover:bg-primary/90'>
                  <Subtitles className='h-4 w-4 mr-2' />
                  Tạo phụ đề cho tất cả video thiếu
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value='upload' className='space-y-6'>
          <Card>
            <CardHeader>
              <CardTitle>Tải lên phụ đề tùy chỉnh</CardTitle>
              <p className='text-sm text-muted-foreground'>Tải tệp phụ đề của bạn ở định dạng SRT, VTT hoặc TXT</p>
            </CardHeader>
            <CardContent>
              <div className='border-2 border-dashed border-border rounded-lg p-12 text-center hover:border-primary/50 transition-colors cursor-pointer'>
                <Upload className='h-12 w-12 mx-auto mb-4 text-muted-foreground' />
                <h3 className='text-lg font-medium mb-2'>Tải tệp phụ đề</h3>
                <p className='text-muted-foreground mb-4'>
                  Kéo và thả tệp phụ đề hoặc nhấn để chọn. Hỗ trợ định dạng SRT, VTT, TXT.
                </p>
                <Button className='bg-primary hover:bg-primary/90'>Chọn tệp phụ đề</Button>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Yêu cầu đối với tệp phụ đề</CardTitle>
            </CardHeader>
            <CardContent className='space-y-4'>
              <div className='grid md:grid-cols-2 gap-4'>
                <div className='space-y-2'>
                  <h4 className='font-medium'>Định dạng được hỗ trợ</h4>
                  <ul className='text-sm text-muted-foreground space-y-1'>
                    <li>• SRT (SubRip Subtitle)</li>
                    <li>• VTT (WebVTT)</li>
                    <li>• TXT (Văn bản có dấu thời gian)</li>
                    <li>• Kích thước tệp tối đa: 10MB</li>
                  </ul>
                </div>
                <div className='space-y-2'>
                  <h4 className='font-medium'>Quy tắc đặt tên tệp</h4>
                  <ul className='text-sm text-muted-foreground space-y-1'>
                    <li>• Tên tệp phải trùng khớp chính xác với video</li>
                    <li>• Thêm mã ngôn ngữ (ví dụ: _en, _es)</li>
                    <li>• Ví dụ: video_en.srt</li>
                    <li>• Sử dụng mã hóa UTF-8</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value='manage' className='space-y-6'>
          <Card>
            <CardHeader>
              <CardTitle>Quản lý phụ đề</CardTitle>
              <p className='text-sm text-muted-foreground'>Xem lại và quản lý phụ đề cho tất cả video khóa học</p>
            </CardHeader>
            <CardContent>
              <div className='space-y-4'>
                {captions.map((caption) => (
                  <div key={caption.id} className='flex items-center space-x-4 p-4 border rounded-lg hover:bg-muted/50'>
                    <div className='flex-shrink-0'>
                      <div className='w-16 h-12 bg-muted rounded flex items-center justify-center'>
                        <Play className='h-6 w-6 text-muted-foreground' />
                      </div>
                    </div>

                    <div className='flex-1 min-w-0'>
                      <div className='flex items-center space-x-2 mb-1'>
                        <h4 className='font-medium truncate'>{caption.videoName}</h4>
                        <Badge variant='outline' className='text-xs'>
                          {caption.language}
                        </Badge>
                        {caption.isAutoGenerated && (
                          <Badge variant='secondary' className='text-xs'>
                            Tự động tạo
                          </Badge>
                        )}
                      </div>
                      <div className='flex items-center space-x-4 text-sm text-muted-foreground'>
                        <span>{caption.duration}</span>
                        {caption.accuracy > 0 && (
                          <span className={getAccuracyColor(caption.accuracy)}>{caption.accuracy}% chính xác</span>
                        )}
                        <span>Cập nhật {caption.uploadDate}</span>
                      </div>
                      {caption.status === 'generating' && (
                        <div className='mt-2'>
                          <Progress value={65} className='h-2' />
                          <div className='flex justify-between text-xs text-muted-foreground mt-1'>
                            <span>Đang tạo phụ đề...</span>
                            <span>65%</span>
                          </div>
                        </div>
                      )}
                    </div>

                    <div className='flex items-center space-x-2'>
                      {getStatusIcon(caption.status)}
                      <span className='text-sm font-medium'>{getStatusText(caption.status)}</span>
                    </div>

                    <div className='flex items-center space-x-1'>
                      <Button variant='ghost' size='icon'>
                        <Eye className='h-4 w-4' />
                      </Button>
                      <Button variant='ghost' size='icon'>
                        <Download className='h-4 w-4' />
                      </Button>
                      <Button variant='ghost' size='icon'>
                        <MoreVertical className='h-4 w-4' />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Nút hành động */}
      <div className='flex justify-between pt-6 border-t'>
        <Button variant='outline'>Trước</Button>
        <div className='space-x-3'>
          <Button variant='outline'>Lưu bản nháp</Button>
          <Button className='bg-primary hover:bg-primary/90'>Tiếp tục</Button>
        </div>
      </div>
    </div>
  )
}

export default CaptionsForm
